export enum AppErrorCode {
  BadRequest = 'BAD_REQUEST',
  Unauthorized = 'UNAUTHORIZED',
  Forbidden = 'FORBIDDEN',
  NotFound = 'NOT_FOUND',
  Conflict = 'CONFLICT',
  ValidationFailed = 'VALIDATION_FAILED',
  RateLimitExceeded = 'RATE_LIMIT_EXCEEDED',
  DatabaseConstraint = 'DATABASE_CONSTRAINT',
  InternalError = 'INTERNAL_ERROR',
  ServiceUnavailable = 'SERVICE_UNAVAILABLE',
  AuthInvalidCredentials = 'AUTH_INVALID_CREDENTIALS',
  AuthRequired = 'AUTH_REQUIRED',
  AuthSessionExpired = 'AUTH_SESSION_EXPIRED',
  AuthRefreshExpired = 'AUTH_REFRESH_EXPIRED',
  AuthRefreshInvalid = 'AUTH_REFRESH_INVALID',
  ActorProfileRequired = 'ACTOR_PROFILE_REQUIRED',
  TenantInactive = 'TENANT_INACTIVE',
  PasswordResetLinkInvalid = 'PASSWORD_RESET_LINK_INVALID',
  OutOfScope = 'OUT_OF_SCOPE',
  DuplicateUserEmail = 'DUPLICATE_USER_EMAIL',
  DuplicateCompanyAbbreviation = 'DUPLICATE_COMPANY_ABBREVIATION',
  DuplicateDivisionAbbreviation = 'DUPLICATE_DIVISION_ABBREVIATION',
  UserRoleAlreadyAssigned = 'USER_ROLE_ALREADY_ASSIGNED',
  StaleUpdate = 'STALE_UPDATE',
}
