ALTER TABLE "documents" DROP CONSTRAINT "documents_project_id_tenant_id_fkey";
ALTER TABLE "documents" DROP CONSTRAINT "documents_work_request_id_project_id_fkey";
ALTER TABLE "work_requests" DROP CONSTRAINT "work_requests_project_id_tenant_id_fkey";
ALTER TABLE "work_requests" DROP CONSTRAINT "work_requests_assigned_division_id_tenant_id_fkey";
ALTER TABLE "work_requests" DROP CONSTRAINT "work_requests_origin_division_id_tenant_id_fkey";
ALTER TABLE "registry_documents" DROP CONSTRAINT "registry_documents_project_id_tenant_id_fkey";
ALTER TABLE "registry_documents" DROP CONSTRAINT "registry_documents_work_request_id_tenant_id_fkey";
ALTER TABLE "registry_documents" DROP CONSTRAINT "registry_documents_document_id_tenant_id_fkey";
ALTER TABLE "actor_profiles" DROP CONSTRAINT "actor_profiles_member_id_tenant_id_fkey";
ALTER TABLE "actor_profiles" DROP CONSTRAINT "actor_profiles_client_contact_id_tenant_id_fkey";
ALTER TABLE "notification_recipients" DROP CONSTRAINT "notification_recipients_notification_id_tenant_id_fkey";
ALTER TABLE "notification_recipients" DROP CONSTRAINT "notification_recipients_actor_id_tenant_id_fkey";
DROP INDEX "documents_project_id_tenant_id_idx"; DROP INDEX "documents_work_request_id_project_id_idx";
DROP INDEX "work_requests_project_id_tenant_id_idx"; DROP INDEX "work_requests_assigned_division_id_tenant_id_idx"; DROP INDEX "work_requests_origin_division_id_tenant_id_idx";
DROP INDEX "registry_documents_project_id_tenant_id_idx"; DROP INDEX "registry_documents_work_request_id_tenant_id_idx"; DROP INDEX "registry_documents_document_id_tenant_id_idx";
DROP INDEX "actor_profiles_member_id_tenant_id_idx"; DROP INDEX "actor_profiles_client_contact_id_tenant_id_idx";
DROP INDEX "notification_recipients_notification_id_tenant_id_idx"; DROP INDEX "notification_recipients_actor_id_tenant_id_idx";
ALTER TABLE "projects" DROP CONSTRAINT "projects_id_tenant_id_key"; ALTER TABLE "divisions" DROP CONSTRAINT "divisions_id_tenant_id_key";
ALTER TABLE "work_requests" DROP CONSTRAINT "work_requests_id_tenant_id_key"; ALTER TABLE "documents" DROP CONSTRAINT "documents_id_tenant_id_key";
ALTER TABLE "members" DROP CONSTRAINT "members_id_tenant_id_key"; ALTER TABLE "client_contacts" DROP CONSTRAINT "client_contacts_id_tenant_id_key";
ALTER TABLE "notifications" DROP CONSTRAINT "notifications_id_tenant_id_key"; ALTER TABLE "actor_profiles" DROP CONSTRAINT "actor_profiles_id_tenant_id_key";
ALTER TABLE "work_requests" DROP CONSTRAINT "work_requests_id_project_id_key";
ALTER TABLE "documents" ADD CONSTRAINT "documents_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "documents" ADD CONSTRAINT "documents_work_request_id_fkey" FOREIGN KEY ("work_request_id") REFERENCES "work_requests"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "work_requests" ADD CONSTRAINT "work_requests_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "work_requests" ADD CONSTRAINT "work_requests_assigned_division_id_fkey" FOREIGN KEY ("assigned_division_id") REFERENCES "divisions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "work_requests" ADD CONSTRAINT "work_requests_origin_division_id_fkey" FOREIGN KEY ("origin_division_id") REFERENCES "divisions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "registry_documents" ADD CONSTRAINT "registry_documents_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "registry_documents" ADD CONSTRAINT "registry_documents_work_request_id_fkey" FOREIGN KEY ("work_request_id") REFERENCES "work_requests"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "registry_documents" ADD CONSTRAINT "registry_documents_document_id_fkey" FOREIGN KEY ("document_id") REFERENCES "documents"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "actor_profiles" ADD CONSTRAINT "actor_profiles_member_id_fkey" FOREIGN KEY ("member_id") REFERENCES "members"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "actor_profiles" ADD CONSTRAINT "actor_profiles_client_contact_id_fkey" FOREIGN KEY ("client_contact_id") REFERENCES "client_contacts"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "notification_recipients" ADD CONSTRAINT "notification_recipients_notification_id_fkey" FOREIGN KEY ("notification_id") REFERENCES "notifications"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "notification_recipients" ADD CONSTRAINT "notification_recipients_actor_id_fkey" FOREIGN KEY ("actor_id") REFERENCES "actor_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
