export const TENANT_ID_HEADER = 'x-tenant-id';

export const TENANT_SCOPED_MODELS = new Set<string>([
  'User',
  'UserRole',
  'ActorProfile',
  'AuthSession',
  'AuthSessionConsumedRefreshToken',
  'PasswordResetToken',
  'Company',
  'Division',
  'Member',
  'Team',
  'TeamMember',
  'Client',
  'ClientContact',
  'PortalConfig',
  'OptionValue',
  'DocumentCodeOption',
  'SourceChannel',
  'Project',
  'ProjectStatusEvent',
  'BidDetail',
  'ProjectCredentialDelivery',
  'BidOutcomeEvent',
  'ProjectConversionEvent',
  'ArchivedBidReviewRequest',
  'DocumentCategory',
  'Document',
  'DocumentVersion',
  'DocumentFolder',
  'DocumentVersionFolderLocation',
  'DocumentVersionLink',
  'WorkRequestCategory',
  'WorkRequestAttachmentCategory',
  'WorkflowTransition',
  'WorkflowActionRolePermission',
  'WorkRequest',
  'WorkRequestAssignment',
  'WorkRequestAuditLog',
  'WorkRequestNote',
  'WorkRequestAuditAttachment',
  'WorkflowInfoRequest',
  'WorkflowInfoResponse',
  'WorkRequestRevisionRequest',
  'WorkRequestRevisionDocument',
  'WorkRequestRevisionSubmission',
  'WorkRequestRevisionSubmissionDocument',
  'WorkRequestDecision',
  'RegistryDocument',
  'Notification',
  'NotificationRecipient',
  'SystemAuditLog',
  // Producers write these inside a request, so the extension injects the tenant
  // for them. The relay reads across tenants and must use `prisma.unscoped`.
  'OutboxMessage',
  'ProcessedEvent',
]);
