-- CreateTable
CREATE TABLE "division_leads" (
    "tenant_id" UUID NOT NULL,
    "id" UUID NOT NULL,
    "company_id" UUID NOT NULL,
    "division_id" UUID NOT NULL,
    "member_id" UUID NOT NULL,
    "assigned_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "assigned_by_user_id" UUID NOT NULL,
    "revoked_at" TIMESTAMP(6),
    "revoked_by_user_id" UUID,

    CONSTRAINT "division_leads_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "division_leads_tenant_id_idx" ON "division_leads"("tenant_id");

-- CreateIndex
CREATE INDEX "division_leads_tenant_id_member_id_revoked_at_idx" ON "division_leads"("tenant_id", "member_id", "revoked_at");

-- CreateIndex
CREATE INDEX "division_leads_tenant_id_division_id_revoked_at_idx" ON "division_leads"("tenant_id", "division_id", "revoked_at");

-- CreateIndex
CREATE UNIQUE INDEX "division_leads_id_tenant_id_key" ON "division_leads"("id", "tenant_id");

-- AddForeignKey
ALTER TABLE "division_leads" ADD CONSTRAINT "division_leads_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "division_leads" ADD CONSTRAINT "division_leads_division_id_tenant_id_company_id_fkey" FOREIGN KEY ("division_id", "tenant_id", "company_id") REFERENCES "divisions"("id", "tenant_id", "company_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "division_leads" ADD CONSTRAINT "division_leads_member_id_tenant_id_fkey" FOREIGN KEY ("member_id", "tenant_id") REFERENCES "members"("id", "tenant_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- ---------------------------------------------------------------------------
-- Hand-written block. Everything below is NOT generated by `prisma migrate`
-- and must survive any regeneration of this migration.
--
-- Spec: specs/04.1.1-division-lead-multiplicity/DATA_CONTRACT.md
--       § Proposed schema change
--
-- Prisma's `@@unique` carries no predicate and Prisma schema cannot express
-- RLS or grants, so the constraints that actually enforce the design live only
-- here. Without this block the table exists but nothing enforces one-active-
-- lead-per-division, no tenant policy applies, and app_user cannot read it.
-- ---------------------------------------------------------------------------

-- SPEC DR-03: at most one ACTIVE Lead per Division.
-- Partial on purpose: revoked rows are retained history (non-negotiable #9)
-- and must not participate in uniqueness.
CREATE UNIQUE INDEX "division_leads_one_active_per_division"
  ON "division_leads" ("tenant_id", "division_id")
  WHERE "revoked_at" IS NULL;

-- SPEC DR-07: the same Member is not ACTIVE twice on one Division, while a
-- Member previously revoked from a Division may be re-assigned to it.
-- A non-partial UNIQUE (tenant_id, division_id, member_id) is explicitly
-- rejected by the contract: retained revoked rows would collide with the new
-- active row and permanently bar re-assignment (SPEC AC-W02).
CREATE UNIQUE INDEX "division_leads_active_pair"
  ON "division_leads" ("tenant_id", "division_id", "member_id")
  WHERE "revoked_at" IS NULL;

-- Tenant isolation, matching the Phase 6 baseline in
-- 20260901000000_enable_tenant_rls. app_user is NOBYPASSRLS and does not own
-- this table, so ENABLE (not FORCE) is the established form here.
ALTER TABLE "division_leads" ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_division_leads ON "division_leads"
  AS PERMISSIVE
  FOR ALL
  TO app_user
  USING ("tenant_id" = current_setting('app.tenant_id')::uuid)
  WITH CHECK ("tenant_id" = current_setting('app.tenant_id')::uuid);

-- Minimum privileges for the assign/revoke/read repository paths, following
-- 20260910142000_app_user_organization_module_grants.
--
-- DELETE is deliberately withheld: SPEC DR-06 and non-negotiable #9 revoke
-- leadership by setting revoked_at, never by deleting the row. Do not add
-- DELETE here without changing that rule first.
--
-- No app_relay grant: the relay holds only its single outbox table, and this
-- module publishes no event (plan.md §4).
--
-- Rollback note: `DROP TABLE "division_leads";` removes the table, both partial
-- indexes and the policy together; the grants need no separate reversal.
GRANT SELECT, INSERT, UPDATE ON TABLE
  "division_leads"
TO app_user;
